"""empty message

Revision ID: 7c3f07df184f
Revises: e7c676e920ad
Create Date: 2020-02-01 21:20:10.327252

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c3f07df184f'
down_revision = 'e7c676e920ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subjects', sa.Column('year', sa.Integer(), nullable=True))
    op.drop_constraint('subjects_name_key', 'subjects', type_='unique')
    op.add_column('users', sa.Column('is_superuser', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superuser')
    op.create_unique_constraint('subjects_name_key', 'subjects', ['name'])
    op.drop_column('subjects', 'year')
    # ### end Alembic commands ###
